In [11]:
import numpy as np
import pandas as pd

In [12]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
x=np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


In [16]:
x=np.random.random((10,10))
xmin,xmax = x.min(),x.max()
print(xmin,xmax)

0.004546935404766805 0.9953338006168772


In [17]:
x=np.random.random(30)
m=x.mean()
print(m)

0.3902815419390842
